### ISSUE TITLE
Segmentation fault (core dumped) when doing nextpnr

### ISSUE THREAD

**Issue by aergun** [PyFive-RISC-V/pyfive-mpw1-postmortem#5]
I get the following error message during the bring-up make sequence:

nextpnr-ice40 --no-promote-globals --pre-pack data/clocks.py --seed 1  \
	--up5k --package sg48  \
	-l /home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/build-tmp/pyfive_test.pnr.rpt \
	--json /home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/build-tmp/pyfive_test.json \
	--pcf /home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/data/top-icebreaker.pcf \
	--asc /home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/build-tmp/pyfive_test.asc
../build/project-rules.mk:91: recipe for target '/home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/build-tmp/pyfive_test.asc' failed
make: *** [/home/ubuntu/testboard/pyfive-mpw1-postmortem/icebreaker/bringup/build-tmp/pyfive_test.asc] Segmentation fault (core dumped)

Do you know what the issue might be? I am on Ubuntu 18.04.5

Thank you

Armagan

**Comment by smunaut** [comment]
You need to report that to nextpnr repo ... it shouldn't ever segfault no matter what.
